import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/NavBar";
import { Inter } from "next/font/google";
import localFont from 'next/font/local';
import TransitionBackground from "./components/TransitionBackground";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const helvetica = localFont({
  src: [
    {
      path: './fonts/HelveticaNeue.woff2',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-helvetica',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${helvetica.variable} antialiased`}
      >
        <TransitionBackground />
        <div className="flex fixed top-10 justify-center items-center w-full">
          <Navbar />
        </div>
        {children}
      </body>
    </html>
  );
}
